apiVersion: v1
kind: Namespace
metadata:
  name: resource-test

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-test-reource-quota
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 500mi
    limits.cpu: "0.5"
    limits.memory: 500mi