apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: naru-colombo
controllerManager: {}
controlPlaneEndpoint: cm.hancomit.com:16443
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.90.128.0/17
  podSubnet: 10.90.0.0/17
apiServer:
  certSANs:
  - 192.168.200.149
  - cm.hancomit.com
scheduler: {}
