apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-test-reource-quota
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 1Gi
    requests.ephemeral-storage: 10Gi
    limits.cpu: "0.5"
    limits.memory: 1Gi
    limits.ephemeral-storage: 50Gi
    
